#!/bin/bash
echo "Enter string: "
read str

len=${#str}
for (( i=$len-1; i>=0; i-- ))
do
    reveres_str="$reveres_str${str:$i:1}"
    
done
if [ "$str" == "$reveres_str" ]
then
    echo "$str is a palindrome"
else
    echo "$str is not a pallindrome"
fi
